### ISSUE TITLE
Use of gpgsm certificates

### ISSUE THREAD

**Issue by madjam002** [sektioneins/scd-pkcs11#7]
Hi,

Just an idea. My current understanding is that scd-pkcs11 requires an authentication x509 certificate to be written to the OpenPGP card certificate slot. Some smartcards (I'm looking at you, Yubikey 4) have a very limited size for data in this slot meaning that a certificate chain and certificate using a RSA 4096 bit key won't fit.

Therefore I was thinking it would be nice to use certificates stored with the `gpgsm` command line, just like scute does. This could also open up the possibility of having multiple certificates exposed as you can store multiple certificates with `gpgsm`.

Interested to know your thoughts. Cheers

**Comment by bef** [comment]
Hi,

thank you for your suggestions. It appears that `scute` is doing almost the same as scd-pkcs11 and they might be mostly interchangeable. Thank you for pointing that out.

As for the Yubikey, there is a PIV-applet available to store X.509 certificates, as well as the corresponding PKCS#11 interface: https://developers.yubico.com/yubico-piv-tool/YKCS11_release_notes.html

Other hardware, e.g. the NitroKey Pro, is able to store the entire X.509 certificate in any of the 3 OpenPGP slots. scd-pkcs11 only supports slot 3 (OPENPGP.3), designated for authentication.
